version: "3.4"
services:
  app:
    container_name: Team5Project6
    build:
      context: ../
      dockerfile: deployments/app/Dockerfile
    ports:
      - "5000:5000"
    networks:
      - webnet
  redis:
    image: redis
    networks:
      - webnet
networks:
  webnet:
